# Generated by Django 3.0 on 2020-04-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='content',
        ),
    ]
