# Generated by Django 3.0 on 2020-04-20 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_remove_quiz_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liste_Expert_Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='gourpe1', max_length=270, verbose_name='Nom : ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='classroom.Student')),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projet', to='classroom.Quiz')),
            ],
        ),
    ]
