# Generated by Django 3.0 on 2020-04-26 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_liste_expert_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='domaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaines_projet', to='classroom.Domaine', verbose_name="Domaine d'application du projet  "),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='subject',
            field=models.ManyToManyField(related_name='projets', to='classroom.Subject', verbose_name='Disciplinaires scientifiques necessaires au projet  '),
        ),
        migrations.AlterField(
            model_name='student',
            name='adresse_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Adresse email de contact : '),
        ),
        migrations.AlterField(
            model_name='student',
            name='domaine',
            field=models.ManyToManyField(help_text='Relativement à vos activités professionnelles.', related_name='domaines_expert', to='classroom.Domaine', verbose_name="Domaines d'applications  "),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='media/', verbose_name='Figure associée à votre profil'),
        ),
        migrations.AlterField(
            model_name='student',
            name='interests',
            field=models.ManyToManyField(related_name='interested_student', to='classroom.Subject', verbose_name='Disciplines scientifiques '),
        ),
    ]
